// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniRumbo.Repositories;

#nullable disable

namespace UniRumboBakend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rutum", b =>
                {
                    b.Property<int>("IdRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ruta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRuta"));

                    b.Property<int>("CuposIda")
                        .HasColumnType("int")
                        .HasColumnName("cupos_ida");

                    b.Property<int>("CuposVuelta")
                        .HasColumnType("int")
                        .HasColumnName("cupos_vuelta");

                    b.Property<string>("DiasRuta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dias_ruta");

                    b.Property<DateTime>("HoraRegreso")
                        .HasColumnType("datetime2")
                        .HasColumnName("hora_regreso");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime2")
                        .HasColumnName("hora_salida");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    b.Property<string>("PuntoDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("punto_destino");

                    b.Property<string>("PuntoOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("punto_origen");

                    b.HasKey("IdRuta");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Ruta", (string)null);
                });

            modelBuilder.Entity("UniRumbo.Repositories.Alojamiento", b =>
                {
                    b.Property<int>("IdAlojamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_alojamiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlojamiento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdAlojamiento")
                        .HasName("PK__Alojamie__2908794AF1C66E30");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Alojamiento", (string)null);
                });

            modelBuilder.Entity("UniRumbo.Repositories.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("estado");

                    b.HasKey("IdEstado")
                        .HasName("PK__Estado__...");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("UniRumbo.Repositories.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__3214EC0723456789");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("UniRumbo.Repositories.Sede", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSede"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdSede")
                        .HasName("PK__Sede__3214EC07ABCDEF12");

                    b.ToTable("Sede", (string)null);
                });

            modelBuilder.Entity("UniRumbo.Repositories.SolicitudAlojamiento", b =>
                {
                    b.Property<int>("IdSoliAlojamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSoliAlojamiento"));

                    b.Property<int>("IdAlojamiento")
                        .HasColumnType("int");

                    b.Property<int>("IdAlojamientoNavigationIdAlojamiento")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoNavigationIdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioNavigationIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdSoliAlojamiento");

                    b.HasIndex("IdAlojamientoNavigationIdAlojamiento");

                    b.HasIndex("IdEstadoNavigationIdEstado");

                    b.HasIndex("IdUsuarioNavigationIdUsuario");

                    b.ToTable("SolicitudAlojamientos");
                });

            modelBuilder.Entity("UniRumbo.Repositories.SolicitudRutum", b =>
                {
                    b.Property<int>("IdSoliRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_SoliRuta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSoliRuta"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdRuta")
                        .HasColumnType("int")
                        .HasColumnName("id_ruta");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdSoliRuta");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdRuta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Solicitud_ruta");
                });

            modelBuilder.Entity("UniRumbo.Repositories.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol")
                        .HasAnnotation("Relational:JsonPropertyName", "id_rol");

                    b.Property<int>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede")
                        .HasAnnotation("Relational:JsonPropertyName", "id_sede");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__4E3E04AD12345678");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSede");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("UniRumbo.Repositories.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<bool>("TipoVehiculo")
                        .HasColumnType("bit")
                        .HasColumnName("tipo_vehiculo");

                    b.HasKey("IdVehiculo");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("Rutum", b =>
                {
                    b.HasOne("UniRumbo.Repositories.Usuario", "Usuario")
                        .WithMany("Ruta")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniRumbo.Repositories.Vehiculo", "Vehiculo")
                        .WithMany("Rutas")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("UniRumbo.Repositories.Alojamiento", b =>
                {
                    b.HasOne("UniRumbo.Repositories.Usuario", "IdUsuarioNavigation")
                        .WithMany("Alojamientos")
                        .HasForeignKey("Id_Usuario")
                        .IsRequired()
                        .HasConstraintName("FK__Alojamien__id_us__34C8D9D1");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("UniRumbo.Repositories.SolicitudAlojamiento", b =>
                {
                    b.HasOne("UniRumbo.Repositories.Alojamiento", "IdAlojamientoNavigation")
                        .WithMany("SolicitudAlojamientos")
                        .HasForeignKey("IdAlojamientoNavigationIdAlojamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniRumbo.Repositories.Estado", "IdEstadoNavigation")
                        .WithMany("SolicitudAlojamientos")
                        .HasForeignKey("IdEstadoNavigationIdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniRumbo.Repositories.Usuario", "IdUsuarioNavigation")
                        .WithMany("SolicitudAlojamientos")
                        .HasForeignKey("IdUsuarioNavigationIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAlojamientoNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("UniRumbo.Repositories.SolicitudRutum", b =>
                {
                    b.HasOne("UniRumbo.Repositories.Estado", "IdEstadoNavigation")
                        .WithMany("SolicitudRuta")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rutum", "IdRutaNavigation")
                        .WithMany()
                        .HasForeignKey("IdRuta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniRumbo.Repositories.Usuario", "IdUsuarioNavigation")
                        .WithMany("SolicitudRuta")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdRutaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("UniRumbo.Repositories.Usuario", b =>
                {
                    b.HasOne("UniRumbo.Repositories.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario__id_rol__2A4B4B5E");

                    b.HasOne("UniRumbo.Repositories.Sede", "IdSedeNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdSede")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario__id_sede__29572725");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("UniRumbo.Repositories.Alojamiento", b =>
                {
                    b.Navigation("SolicitudAlojamientos");
                });

            modelBuilder.Entity("UniRumbo.Repositories.Estado", b =>
                {
                    b.Navigation("SolicitudAlojamientos");

                    b.Navigation("SolicitudRuta");
                });

            modelBuilder.Entity("UniRumbo.Repositories.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("UniRumbo.Repositories.Sede", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("UniRumbo.Repositories.Usuario", b =>
                {
                    b.Navigation("Alojamientos");

                    b.Navigation("Ruta");

                    b.Navigation("SolicitudAlojamientos");

                    b.Navigation("SolicitudRuta");
                });

            modelBuilder.Entity("UniRumbo.Repositories.Vehiculo", b =>
                {
                    b.Navigation("Rutas");
                });
#pragma warning restore 612, 618
        }
    }
}
